title: Iqbal Fariz Novirianto
logo: /assets/img/profil_cv.jpg
description: > 
About Me
- email : iqball.frz@gmail.com
- handphone : +6287798021342
- LinkedIn : [LinkedIn](https://www.linkedin.com/in/iqbal-fn/)
theme: jekyll-theme-minimal
