title: Iqbal Fariz Novirianto
logo: /assets/img/profil_circle_resize.png
description : I am an Android developer who enjoys working in collaborative teams and continuously strives to gain valuable experience in order to create exceptional Android apps.
theme: jekyll-theme-minimal
